@startuml approval

skinparam style strictuml

actor admin
boundary dashboard <<boundary>>
boundary "user-management" as management <<boundary>>
control UserController <<control>>
entity User <<entity>>

admin -> dashboard : masuk ke menu\nuser management
    activate dashboard 
dashboard -> management : memilih menu approve\npada teknisi yang akan\ndisetujui pendaftarannya
    deactivate dashboard
    activate management
management -> UserController : memproses\npermintaan
    activate UserController
UserController -> User : memberikan flag disetujui\npada data teknisi yang\ndisetujui pendaftarannya
    activate User 
return berhasil
UserController -> management : berhasil\nmenyetujui
    deactivate UserController
management -> admin : pesan persetujuan pendaftaran teknisi berhasil

@enduml