@startuml createCM

skinparam style strictuml

actor teknisi
boundary "cm-reports" as cm <<boundary>>
boundary "cm-create" as cmCreate <<boundary>>
control ReportController <<control>>
entity HeadReport <<entity>>
entity ExpertReport <<entity>>
entity CmBodyReport <<entity>>
entity Recommendation <<entity>>
entity ReportImage <<entity>>

ref over teknisi, cm : Menampilkan\nSemua Laporan CM

activate cm
cm -> cmCreate : teknisi\nmengisi\nform
    deactivate cm
    activate cmCreate
cmCreate -> ReportController : verifikasi input
    deactivate cmCreate
    activate ReportController

alt data sesuai
    ReportController -> HeadReport : bagian kepala\ndari laporan
        activate HeadReport
        return berhasil
    ReportController -> ExpertReport : teknisi yang bertugas\npada laporan
        activate ExpertReport
        return berhasil
    ReportController -> CmBodyReport : bagian badan dari laporan
        activate CmBodyReport
        return berhasil
    ReportController -> Recommendation : bagian rekomendasi sparepart
        activate Recommendation
        return berhasil
    ReportController -> ReportImage : bagian lampiran
        activate ReportImage
        return berhasil
    ReportController -> cm : teknisi dipindahkan
        activate cm
    cm -> teknisi : pesan\nberhasil
        deactivate cm
    
else data tidak sesuai
    ReportController -> cmCreate : masukan\ntidak sesuai
        deactivate ReportController
        activate cmCreate
    cmCreate --> teknisi : pesan masukan\ntidak sesuai
        deactivate cmCreate

end

@enduml



@startuml viewCM

skinparam style strictuml

actor teknisi
boundary dashboard <<boundary>>
boundary "cm-reports" as cm <<boundary>>
boundary "cm-item" as cmItem <<boundary>>

ref over teknisi, cm : Menampilkan\nSemua Laporan CM

activate cm
cm -> cmItem : teknisi memilih\nlaporan
    deactivate cm
    activate cmItem
cmItem -> cmItem : menampilkan\ndata laporan

@enduml



@startuml editCM

skinparam style strictuml

actor teknisi
boundary "cm-item" as cmItem <<boundary>>
boundary "cm-create" as cmCreate <<boundary>>
control ReportController <<control>>
entity HeadReport <<entity>>
entity ExpertReport <<entity>>
entity CmBodyReport <<entity>>
entity Recommendation <<entity>>
entity ReportImage <<entity>>

ref over teknisi, cmItem : Melihat Laporan PM

activate cmItem
cmItem -> cmCreate : mengisi form\ndengan\ndata lama
    deactivate cmItem
cmCreate -> ReportController : verifikasi input
    activate ReportController

alt data sesuai
    ReportController -> HeadReport : bagian kepala\ndari laporan
        activate HeadReport
        return berhasil
    ReportController -> ExpertReport : teknisi yang bertugas\npada laporan
        activate ExpertReport
        return berhasil
    ReportController -> CmBodyReport : bagian badan dari laporan
        activate CmBodyReport
        return berhasil
    ReportController -> Recommendation : bagian rekomendasi sparepart
        activate Recommendation
        return berhasil
    ReportController -> ReportImage : bagian lampiran
        activate ReportImage
        return berhasil
    ReportController -> cmItem : teknisi dipindahkan
        activate cmItem
    cmItem -> teknisi : pesan\nberhasil
        deactivate cmItem
    
else data tidak sesuai
    ReportController -> cmCreate : masukan\ntidak sesuai
        deactivate ReportController
    cmCreate --> teknisi : pesan masukan\ntidak sesuai
        deactivate cmCreate
end

@enduml



@startuml deleteCM

skinparam style strictuml

actor teknisi
boundary "cm-reports" as cm <<boundary>>
boundary "cm-item" as cmItem <<boundary>>
control ReportController <<control>>
entity HeadReport <<entity>>

ref over teknisi, cmItem : Melihat Laporan PM

cmItem -> ReportController : teknisi memilih\nmenu delete
    deactivate cmItem
    activate ReportController
ReportController -> HeadReport : data diberikan\nflag dihapus
    activate HeadReport
    return berhasil
ReportController -> cm : teknisi dipindahkan
    activate cm
cm --> teknisi : pesan\nberhasil
    deactivate cm

@enduml