@startuml downloadPM 

skinparam style strictuml

actor teknisi
boundary "pm-item" as item <<boundary>>
control PDFController <<control>>

teknisi -> item : teknisi memilih\nmenu download
    activate item
item -> PDFController : mengunduh file\nmelalui browser
    deactivate item
    activate PDFController
PDFController -> teknisi : teknisi menerima file

@enduml



@startuml downloadCM 

skinparam style strictuml

actor teknisi
boundary "cm-item" as item <<boundary>>
control PDFController <<control>>

teknisi -> item : teknisi memilih\nmenu download
    activate item
item -> PDFController : mengunduh file\nmelalui browser
    deactivate item
    activate PDFController
PDFController -> teknisi : teknisi menerima file

@enduml