@startuml downloadPM 

skinparam style strictuml

actor teknisi
boundary "pm-item" as item <<boundary>>
control PDFController <<control>>

ref over teknisi, item : Melihat Laporan PM

teknisi -> item : teknisi masuk\nke item laporan
    activate item
item -> PDFController : teknisi memilih\nmenu download
    deactivate item
    activate PDFController
PDFController -> PDFController : mengunduh file\nmelalui browser

@enduml



@startuml downloadCM 

skinparam style strictuml

actor teknisi
boundary "cm-item" as item <<boundary>>
control PDFController <<control>>

ref over teknisi, item : Melihat Laporan CM

teknisi -> item : teknisi masuk\nke item laporan
    activate item
item -> PDFController : teknisi memilih\nmenu download
    deactivate item
    activate PDFController
PDFController -> PDFController : mengunduh file\nmelalui browser

@enduml