@startuml permDeletePM

skinparam style strictuml

actor teknisi
boundary "pm-trash" as trash <<boundary>>
control TrashController <<control>>
entity HeadReport <<entity>>
entity ExpertReport <<entity>>
entity PmBodyReport <<entity>>
entity Recommendation <<entity>>
entity ReportImage <<entity>>

teknisi -> trash : teknisi\nmemilih ikon\ndelete pada\nitem laporan
    activate trash
trash -> TrashController : melakukan delete
    activate TrashController
TrashController -> HeadReport : menghapus data\ndari database
    activate HeadReport
    return berhasil
TrashController -> ExpertReport : menghapus data\ndari database
    activate ExpertReport
    return berhasil
TrashController -> PmBodyReport : menghapus data\ndari database
    activate PmBodyReport
    return berhasil
TrashController -> Recommendation : menghapus data\ndari database
    activate Recommendation
    return berhasil
TrashController -> ReportImage : menghapus data\ndari database
    activate ReportImage
    return berhasil

TrashController -> trash : berhasil\nmenghapus
    deactivate TrashController
trash --> teknisi : pesan laporan\nberhasil dihapus\nsecara permanen
    deactivate trash

@enduml



@startuml permDeleteCM

skinparam style strictuml

actor teknisi
boundary "cm-trash" as trash <<boundary>>
control TrashController <<control>>
entity HeadReport <<entity>>
entity ExpertReport <<entity>>
entity CmBodyReport <<entity>>
entity Recommendation <<entity>>
entity ReportImage <<entity>>

teknisi -> trash : teknisi\nmemilih ikon\ndelete pada\nitem laporan
    activate trash
trash -> TrashController : melakukan delete
    activate TrashController
trash -> TrashController : teknisi\nmemilih ikon\ndelete pada\nitem laporan

TrashController -> HeadReport : menghapus data\ndari database
    activate HeadReport
    return berhasil
TrashController -> ExpertReport : menghapus data dari database
    activate ExpertReport
    return berhasil
TrashController -> CmBodyReport : menghapus data dari database
    activate CmBodyReport
    return berhasil
TrashController -> Recommendation : menghapus data dari database
    activate Recommendation
    return berhasil
TrashController -> ReportImage : menghapus data dari database
    activate ReportImage
    return berhasil

TrashController -> trash : berhasil\nmenghapus
    deactivate TrashController
trash --> teknisi : pesan laporan\nberhasil dihapus\nsecara permanen
    deactivate trash

@enduml