@startuml printPM 

skinparam style strictuml

actor teknisi
boundary "pm-item" as item <<boundary>>
boundary "pm-print" as print <<boundary>>

teknisi -> item : teknisi memilih\nmenu print
    activate item
item -> print : teknisi dipindahkan\nke halaman print
    deactivate item
    activate print
print -> print : mencetak halaman\nke bentuk pdf

@enduml



@startuml printCM

skinparam style strictuml

actor teknisi
boundary "cm-item" as item <<boundary>>
boundary "cm-print" as print <<boundary>>

teknisi -> item : teknisi memilih\nmenu print
    activate item
item -> print : teknisi dipindahkan\nke halaman print
    deactivate item
    activate print
print -> print : mencetak halaman\nke bentuk pdf

@enduml