@startuml restorePM

skinparam style strictuml

actor teknisi
boundary "pm-trash" as trash <<boundary>>
control TrashController <<control>>
entity HeadReport <<entity>>

teknisi -> trash : teknisi\nmemilih ikon\nrestore pada\nitem laporan
    activate trash
trash -> TrashController : melakukan restore
    activate TrashController
TrashController -> HeadReport : menghapus\nflag "dihapus"\npada\nitem laporan
    activate HeadReport
    return berhasil
TrashController -> trash : berhasil merestore
    deactivate TrashController
trash --> teknisi : pesan laporan\nberhasil di restore
    deactivate trash

@enduml



@startuml restoreCM

skinparam style strictuml

actor teknisi
boundary "cm-trash" as trash <<boundary>>
control TrashController <<control>>
entity HeadReport <<entity>>

teknisi -> trash : teknisi\nmemilih ikon\nrestore pada\nitem laporan
    activate trash
trash -> TrashController : melakukan restore
    activate TrashController
TrashController -> HeadReport : menghapus\nflag "dihapus"\npada\nitem laporan
    activate HeadReport
    return berhasil
TrashController -> trash : berhasil merestore
    deactivate TrashController
trash --> teknisi : pesan laporan\nberhasil di restore
    deactivate trash

@enduml