@startuml viewStocks

skinparam style strictuml

actor teknisi
boundary dashboard <<boundary>>
boundary stocks <<boundary>>

teknisi->dashboard : teknisi memilih\nmenu stok\nsuku cadang
    activate dashboard
dashboard -> stocks : teknisi\ndipindahkan ke\nhalaman stocks
    deactivate dashboard
    activate stocks
stocks -> stocks : menampilkan\nseluruh laporan stok\nsuku cadang\nyang tersedia

@enduml