@startuml viewAllPM

skinparam style strictuml

actor teknisi
boundary dashboard <<boundary>>
boundary "pm-reports" as pm <<boundary>>

teknisi -> dashboard : teknisi memilih\nmenu PM Reports
    activate dashboard
dashboard -> pm : teknisi\ndipindahkan\nke halaman PM
    deactivate dashboard
    activate pm
pm -> pm : menampilkan\nseluruh laporan PM\nyang belum dihapus

@enduml



@startuml viewAllCM

skinparam style strictuml

actor teknisi
boundary dashboard <<boundary>>
boundary "cm-reports" as cm <<boundary>>

teknisi -> dashboard : teknisi memilih\nmenu CM Reports
    activate dashboard
dashboard -> cm : teknisi\ndipindahkan\nke halaman CM
    deactivate dashboard
    activate cm
cm -> cm : menampilkan\nseluruh laporan CM\nyang belum dihapus

@enduml